### ISSUE TITLE
github授权登录出现 "message": "Not Found"

### ISSUE THREAD

**Issue by wei98k** [Yurunsoft/YurunOAuthLogin#2]
当我修改这行: https://github.com/Yurunsoft/YurunOAuthLogin/blob/7a9e390d3facf150dfb4df5192fc593201ab5127/src/Github/OAuth2.php#L65

`$this->getUrl` 修改成 `$this->getAuthLoginUrl`就执行成功, 我没有看到可配置的选项. 
### 错误信息截图
![images](http://images.majianwei.com/201818040638-a.png)

**Comment by Yurunsoft** [comment]
确实有这个问题，之前改代码时候复制粘贴可能弄错了。如果方便的话提交个PR吧？
