### ISSUE TITLE
Class 'Yurun\OAuthLogin\Weixin\OAuth2' not found

### ISSUE THREAD

**Issue by aben1188** [Yurunsoft/YurunOAuthLogin#4]
在phpstorm中，在loginPC.php文件的类名上按ctrl+b，能自动跳转到类定义处，说明autoload是正常的，但一运行就报错：Class 'Yurun\OAuthLogin\Weixin\OAuth2' not found。

排查了很久，仍然报错。请问如何解决？谢谢！

**Comment by Yurunsoft** [comment]
在项目`composer.json`中引入本项目，然后执行`composer update`
