### ISSUE TITLE
2个项目的共存？

### ISSUE THREAD

**Issue by ZhangChengLin** [Yurunsoft/YurunOAuthLogin#7]
https://github.com/thephpleague/oauth2-client

咱们这个项目和上面网址这个项目的区别大么？可以共存使用吗？

**Comment by zhangchenglin** [comment]
https://github.com/justauth/justauth-php

刚看到这个  推荐给你
@Yurunsoft

**Comment by Yurunsoft** [comment]
不冲突

**Comment by Yurunsoft** [comment]
不要打广告，谢谢

**Comment by ZhangChengLin** [comment]
没有想打广告，只是看你的项目都是关于PHP的，所以说了2句，另外发现那个人数比较多的oauth项目也准备做PHP版了，这次不打广告了好不，不说名字了。
没准在那可以更好点。

**Comment by ZhangChengLin** [comment]
如有打扰，请删除本条整个ISSUES
